; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "inno_setup_conf.txt"
OutputBaseFilename=perso4_64_setup

[Files]
Source: "perso.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\perso\share64\*"; DestDir: "{app}\share"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Documents\perso\LibO\*"; DestDir: "{app}\LibO"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Documents\perso\fichiers\*"; DestDir: "{app}\fichiers"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Documents\perso\dll64\*.dll"; DestDir: "{app}"; Flags: ignoreversion
; Source: "E:\usr\x86_64-w64-mingw32\sys-root\mingw\bin\*.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCR; Subkey: "person-file\DefaultIcon"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "{app}\fichiers\glade\Images\add.ico"
Root: HKCR; Subkey: "person-file\shell\open\command"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "{app}\perso.exe"
Root: HKCR; Subkey: ".pers"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "persfile"
Root: HKCR; Subkey: ".grp"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "grpfile"
Root: HKCR; Subkey: "persfile"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "Feuille de personnage ADD"
Root: HKCR; Subkey: "persfile\DefaultIcon"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "{app}\perso.exe, 1"
Root: HKCR; Subkey: "persfile\shell\open\command"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: """{app}\perso.exe"" ""%1"""
Root: HKCR; Subkey: "grpfile"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "Groupe de personnagges ADD"
Root: HKCR; Subkey: "grpfile\DefaultIcon"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: "{app}\perso.exe, 1"
Root: HKCR; Subkey: "grpfile\shell\open\command"; Flags: uninsdeletekey; ValueType: string; ValueName: ""; ValueData: """{app}\perso.exe"" ""%1"""
